# theme: jekyll-theme-cayman
theme: minima
# theme: beautiful-jekyll-theme
# https://github.com/daattali/beautiful-jekyll#readme

url: https://yogabeauchef.github.io

lang: es
timezone: Chile/Santiago
date_format: "%d de %B, %Y"

google_analytics: UA-83579468-1
google_analytics_id: UA-83579468-1

# event is a post about our past event
# news is a post about upcoming events or other organizational information
# post is any other kind of post

defaults:
  -
    scope:
      path: ""
    values:
      print-title: true

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
    output: true

# Name of website
title: Yoga Beauchef
name: Yoga Beauchef • Conocete a Ti Mismo
description: Grupo Yoga Beauchef organiza un taller de Yoga &amp; Desarrollo Humano, entendiendo la Yoga, como una herramienta para nuestro desarrollo integral.
logo: /assets/img/logo/mini.png


# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Notícias & Artículos: 'articulos.html'
  Taller:
    - Yoga & D.H.: 'detalles.html'
    - Contenido: "taller.html"
    - Inscripciones FCFM: "http://eepurl.com/cD1YXj"
  Lugares: "lugares.html"
    # - FCFM: "lugares.html#fcfm"
    # - FAU: "lugares.html#fau"
    # - FEN: "lugares.html#fen"
    # - JGM: "lugares.html#jgm"
      
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/logo/mini.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Yoga Beauchef
  email: "YogaBeauchef@ing.uchile.cl"
  facebook: yogabeauchef
  
# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
